---
- hosts: localhost
  pre_tasks:
    - name: Check Homebrew Installation
      stat:
        path: /usr/local/bin/brew
      register: homebrew_check

    - name: Installing Homebrew
      shell: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
      when:
        - not homebrew_check.stat.exists

    - name: Create inventory file
      shell: touch inventory && echo "[localhost\]" > inventory && echo "$(hostname)" >> inventory

  vars_prompt:
    - name: user
      private: false
      prompt: "What is your username?"
      salt_size: 8

  vars:
    dotfiles_repo: "https://github.com/camerow/dotfiles.git"
    neovim_config_repo: "https://github.com/camerow/nvim.git"
    ssh_key: ".ssh/id_rsa"
    source_key: "./.ssh/id_rsa"
    dest_key: "$HOME/.ssh/id_rsa"
    personal: "$HOME/personal"

  tasks:
    - include: tasks/ssh.yml
      tags: ["ssh"]
    - include: tasks/node-setup.yml
      tags: ["node"]
    - include: tasks/zsh-setup.yml
      tags: ["zsh"]
    - include: tasks/dotfiles.yml
      tags: ["dotfiles"]
    - include: tasks/neovim.yml
      tags: ["neovim"]
